export interface WorkItem {
  title: string;
  year: number;
  description: string;
  summary: string;
  url?: string | null;
  slug?: string;
  role?: string;
  actionLabel?: string;
  linkLabel?: string;
  capabilities: string[];
}

export const workItems: WorkItem[] = [
  {
    title: "GetSociable",
    year: 2026,
    description: "Ran a full UX audit of a live consumer mobile app covering onboarding, home feed, discovery, map, itinerary planning, and social features. Audited the existing Figma design system for consistency gaps.",
    summary: "UX audit for a live consumer mobile app.",
    url: "https://getsociable.app/",
    slug: "getsociable",
    role: "UX Design Placement",
    capabilities: ["UX Research", "Design Systems", "Figma"],
    actionLabel: "Read about GetSociable",
    linkLabel: "Visit Live Project",
  },
  {
    title: "Ichie",
    year: 2026,
    description: "Helps people remember and follow up with the people they meet at events. An offline-first personal CRM for intentional networking.",
    summary: "Event memory app. Designed the system and built it in React.",
    url: "https://ichie-web.vercel.app/",
    slug: "ichie",
    capabilities: ["Product Design", "Design Systems", "Frontend"],
    actionLabel: "Read the Ichie case study",
    linkLabel: "Visit Live Project"
  },
  {
    title: "Community Christmas Map",
    year: 2026,
    description: "Helps people find nearby community Christmas events and feel less isolated over the holidays. Created for Marmalade Trust with Scottish Tech Army.",
    summary: "Map app for community Christmas events. Leading design.",
    url: null,
    slug: "community-christmas-map",
    capabilities: ["Product Design", "Frontend"],
    actionLabel: "Read the case study",
  },
  {
    title: "CCPower – Fleet Management System",
    year: 2026,
    description: "Gives fleet teams one place to manage inspections, repairs, and finances. Built for clearer day-to-day operations.",
    summary: "Fleet management platform. Built inspection, repair, and billing modules.",
    url: "https://www.ccpwr.com/",
    slug: "ccpower",
    capabilities: ["Frontend"],
    actionLabel: "Read the CCPower case study",
    linkLabel: "Visit company website",
  },
  {
    title: "London Coffee Roasters",
    year: 2026,
    description: "A polished mobile coffee app concept for people discovering speciality roasters. Built around a warm, distinctive visual system.",
    summary: "Coffee app design system. Built from scratch in Figma.",
    url: "https://v0-wes-anderson-coffee.vercel.app/",
    slug: "london-coffee-roasters",
    capabilities: ["Visual Design", "Design Systems"],
    actionLabel: "Read the case study",
    linkLabel: "Visit Live Project"
  },
  {
    title: "Cafe Immersive Experience",
    year: 2026,
    description: "An immersive cafe experience that explores how people move through and interact with a space. Created as part of an MA project at Birkbeck.",
    summary: "360° cafe experience. An immersive spatial design project.",
    url: null,
    slug: "cafe-immersive-experience",
    capabilities: ["Interaction Design", "Prototyping"],
    actionLabel: "Read the case study",
  },
  {
    title: "Orbit Four",
    year: 2025,
    description: "Lets customers and administrators manage domains with confidence. Built for a smoother registrar experience.",
    summary: "Domain registrar platform. Built the user and admin portals in Vue and Nuxt.",
    url: "https://www.orbitfour.com/",
    slug: "orbit-four",
    capabilities: ["Frontend", "Full Stack"],
    actionLabel: "Read the Orbit Four case study",
    linkLabel: "Visit Live Project",
  },
  {
    title: "Miller Johnson",
    year: 2024,
    description: "Helps internal teams move work through their day with less friction. Designed for clearer operational workflows.",
    summary: "Internal workflow tool. Built with Next.js and Material UI.",
    url: "https://millerjohnson.com/",
    slug: "miller-johnson",
    capabilities: ["Frontend"],
    actionLabel: "Read about Miller Johnson project",
    linkLabel: "Visit company website",
  },
  {
    title: "Andy J. Egan Co. – PurchasePointe",
    year: 2024,
    description: "Helps purchasing teams receive materials and track orders with less manual work. Part of Andy J. Egan's internal platform.",
    summary: "Purchase order platform. Built the Angular receiving module.",
    url: "https://www.andyegan.com/",
    slug: "andy-j-egan-co-purchasepointe",
    capabilities: ["Frontend"],
    actionLabel: "Explore the receiving module",
    linkLabel: "Visit company website",
  },
  {
    title: "JC Electric, Inc.",
    year: 2023,
    description: "Reduces repetitive admin work for internal teams. Built to make everyday operations more efficient.",
    summary: "Internal automation tool. Built with Quasar and Directus.",
    url: "https://www.jcelectric.online/",
    slug: "jc-electric-inc",
    capabilities: ["Frontend"],
    actionLabel: "Read the JC Electric case study",
    linkLabel: "Visit company website",
  },
  {
    title: "Andy J. Egan Company",
    year: 2023,
    description: "Time tracking and credentialing tools used daily by 300+ field workers. Built for a more reliable workforce workflow.",
    summary: "Workforce platform. Built time entry and credentialing modules in Angular.",
    url: "https://www.andyegan.com/",
    slug: "andy-j-egan-company",
    capabilities: ["Frontend"],
    actionLabel: "Explore the workforce platform",
    linkLabel: "Visit company website",
  },
  {
    title: "HealthOpx",
    year: 2022,
    description: "Connects community organisations, hospitals, and insurers around better care. Built to support value-based partnerships.",
    summary: "Healthcare connections platform. Built the React frontend.",
    url: "https://healthopx.com/",
    slug: "healthopx",
    capabilities: ["Frontend"],
    actionLabel: "Read the HealthOpx case study",
    linkLabel: "Visit Live Project",
  },
  {
    title: "GT Independence",
    year: 2021,
    description: "Gives financial services teams a simpler way to manage their data. Built for faster, clearer daily decisions.",
    summary: "Financial services dashboard. Built with Vue 3 and Tailwind.",
    url: "https://gtindependence.com/",
    slug: "gt-independence",
    capabilities: ["Frontend"],
    actionLabel: "Read the GT Independence case study",
    linkLabel: "Visit company website",
  },
  {
    title: "Element 22",
    year: 2021,
    description: "Makes business loan applications easier to complete on any device. Designed around a clear, responsive journey.",
    summary: "Business loan platform. Built the application UI.",
    url: "https://exchange.element22cg.com/",
    slug: "element-22",
    capabilities: ["Frontend"],
    actionLabel: "Read about Element 22",
    linkLabel: "Visit Live Project",
  },
  {
    title: "The Kalamazoo Promise",
    year: 2020,
    description: "Helps students apply for scholarships and track each submission. Designed to make an important process feel straightforward.",
    summary: "Scholarship portal. Built the application and tracking flow.",
    url: "https://portal.kalamazoopromise.com/",
    slug: "the-kalamazoo-promise",
    capabilities: ["Frontend"],
    actionLabel: "Explore the scholarship portal",
    linkLabel: "Visit Live Project",
  },
  {
    title: "COVIDINDIA.ORG",
    year: 2020,
    description: "Made live COVID-19 data easier for people in India to understand. Presented key updates through clear visualisations.",
    summary: "COVID data platform. Built the Highcharts visualisations.",
    url: "https://covidindia.org/",
    slug: "covidindia-org",
    capabilities: ["Frontend"],
    actionLabel: "Read about COVIDINDIA.ORG",
    linkLabel: "Visit Live Project",
  },
];
